config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'
  
  resources :restaurants do 
    get '/restaurants/:id', to: 'restaurants#show', as: 'show_restaurant'
    get '/restaurants', to: 'restaurants#index', as: 'index_restaurant'
    get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
    post '/restaurants', to: 'restaurants#create', as: 'create_restaurant'
    patch '/restaurants/:id', to: 'restaurants#update', as: 'update_restaurant'
    delete '/restaurants/:id', to: 'restaurants#destroy', as: 'destroy_restaurant'
  end
  
  resources :items do
    get '/items/:id', to: 'items#show', as: 'show_item'
    get '/items', to: 'items#index', as: 'index_item'
    get '/items/new', to: 'items#new', as: 'new_item'
    post '/items', to: 'items#create', as: 'create_item'
    patch '/items/:id', to: 'items#update', as: 'update_item'
    delete '/items/:id', to: 'items#destroy', as: 'destroy_item'
  end
  
  resources :dishes do
    get '/dishes/:id', to: 'dishes#show', as: 'show_dish'
    get '/dishes', to: 'dishes#index', as: 'index_dish'
    get '/dishes/new', to: 'dishes#new', as: 'new_dish'
    post '/dishes', to: 'dishes#create', as: 'create_dish'
    patch '/dishes/:id', to: 'dishes#update', as: 'update_dish'
    delete '/dishes/:id', to: 'dishes#destroy', as: 'destroy_dish'
  end

  resources :restaurants do
    resources :items
  end
  
  resources :items
  root 'home#index'

  get '/categories', to: 'home#categories', as: 'categories'
  post '/restaurants/search', to: 'restaurants#search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @top_restaurants = Restaurant.order(items_count: :desc).limit(3)
  end

  def categories
    @categories = Dish.distinct.pluck(:name).sort_by do |category|
      case category
      when 'Entradas'
        1
      when 'Platos Principales'
        2
      when 'Postres'
        3
      else
        4
      end
    end
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/categories.html.erb
<h2><%= @restaurant.name %></h2>

<div class="accordion" id="accordionExample">
  <% @categories.each_with_index do |category, index| %>
    <% main_dishes = @restaurant.items.select { |item| item.dish.name == category } %>
    <div class="accordion-item">
      <h2 class="accordion-header" id="heading<%= index %>">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="false" aria-controls="collapse<%= index %>">
          <%= category %>
        </button>
      </h2>
      <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <% if main_dishes.any? %>
            <ul>
              <% main_dishes.each do |item| %>
                <li><%= item.name %></li>
              <% end %>
            </ul>
          <% else %>
            <p>No dishes found for this category.</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const accordions = document.querySelectorAll('.accordion-item');
    accordions.forEach(function (accordion) {
      const button = accordion.querySelector('.accordion-button');
      const collapse = accordion.querySelector('.accordion-collapse');

      button.addEventListener('click', function () {
        collapse.classList.toggle('show');
      });
    });
  });
</script>

<%= link_to root_path, class: "back-button" do %>
    <button>
      <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1024 1024">
        <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0 188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021 28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 874.690416 484.217237 874.690416 495.52477z"></path>
      </svg>
      <span>Back</span>
    </button>
  <% end %>
</section>

app/views/home/categories.js.erb
$('#categories-container').html('<%= j render "categories" %>');

app/views/home/index.html.erb
<section>
  <h2>Top Restaurants</h2>
  <% @top_restaurants.each do |restaurant| %>
    <div class="restaurant-card">
      <h3><%= restaurant.name %></h3>
      <%= link_to 'Show this restaurant', restaurant_path(restaurant), class: 'btn btn-primary' %>
      <%= link_to 'See more', categories_path(restaurant_id: restaurant.id), class: 'btn btn-primary' %>
    </div>
  <% end %>
</section>