config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'
  
  resources :restaurants do 
    get '/restaurants/:id', to: 'restaurants#show', as: 'show_restaurant'
    get '/restaurants', to: 'restaurants#index', as: 'index_restaurant'
    get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
    post '/restaurants', to: 'restaurants#create', as: 'create_restaurant'
    patch '/restaurants/:id', to: 'restaurants#update', as: 'update_restaurant'
    delete '/restaurants/:id', to: 'restaurants#destroy', as: 'destroy_restaurant'
  end
  
  resources :items do
    get '/items/:id', to: 'items#show', as: 'show_item'
    get '/items', to: 'items#index', as: 'index_item'
    get '/items/new', to: 'items#new', as: 'new_item'
    post '/items', to: 'items#create', as: 'create_item'
    patch '/items/:id', to: 'items#update', as: 'update_item'
    delete '/items/:id', to: 'items#destroy', as: 'destroy_item'
  end
  
  resources :dishes do
    get '/dishes/:id', to: 'dishes#show', as: 'show_dish'
    get '/dishes', to: 'dishes#index', as: 'index_dish'
    get '/dishes/new', to: 'dishes#new', as: 'new_dish'
    post '/dishes', to: 'dishes#create', as: 'create_dish'
    patch '/dishes/:id', to: 'dishes#update', as: 'update_dish'
    delete '/dishes/:id', to: 'dishes#destroy', as: 'destroy_dish'
  end

  resources :restaurants do
    resources :items
  end
  
  resources :items
  root 'home#index'

  get '/categories', to: 'home#categories', as: 'categories'
  post '/restaurants/search', to: 'restaurants#search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  




end

app/models/dish.rb
class Dish < ApplicationRecord
    validates :name, presence: true
    has_many :items



end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
    @dish = Dish.find(params[:id])
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.items.destroy_all
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.fetch(:dish, {}).permit(:name)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Show this dish", @dish %> |
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/index.html.erb
<h1>Dishes</h1>

<% @dishes.each do |dish| %>
  <div>
    <h2>Name: <%= dish.name %></h2>
    <p>
      <%= link_to 'Show this dish', dish, class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>

<%= link_to 'New Dish', new_dish_path, class: 'btn btn-primary' %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= form_with(model: @dish, url: dishes_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back to Dishes', dishes_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/dishes/show.html.erb
<h1>Dish Details</h1>

<% if flash[:success] %>
  <p style="color: green"><%= flash[:success] %></p>
<% end %>

<h2>Name: <%= @dish.name %></h2>

<div>
  <% @dish.items.each do |item| %>
    <p>Name: <%= item.name %></p>
  <% end %>
</div>

<p>
  <%= link_to 'Edit Dish', edit_dish_path(@dish), class: 'btn btn-primary' %>
  <%= link_to 'Destroy this Dish', @dish, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <%= link_to 'Back to Dishes', dishes_path, class: 'btn btn-secondary' %>
</p>