config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'
  
  resources :restaurants do 
    get '/restaurants/:id', to: 'restaurants#show', as: 'show_restaurant'
    get '/restaurants', to: 'restaurants#index', as: 'index_restaurant'
    get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
    post '/restaurants', to: 'restaurants#create', as: 'create_restaurant'
    patch '/restaurants/:id', to: 'restaurants#update', as: 'update_restaurant'
    delete '/restaurants/:id', to: 'restaurants#destroy', as: 'destroy_restaurant'
  end
  
  resources :items do
    get '/items/:id', to: 'items#show', as: 'show_item'
    get '/items', to: 'items#index', as: 'index_item'
    get '/items/new', to: 'items#new', as: 'new_item'
    post '/items', to: 'items#create', as: 'create_item'
    patch '/items/:id', to: 'items#update', as: 'update_item'
    delete '/items/:id', to: 'items#destroy', as: 'destroy_item'
  end
  
  resources :dishes do
    get '/dishes/:id', to: 'dishes#show', as: 'show_dish'
    get '/dishes', to: 'dishes#index', as: 'index_dish'
    get '/dishes/new', to: 'dishes#new', as: 'new_dish'
    post '/dishes', to: 'dishes#create', as: 'create_dish'
    patch '/dishes/:id', to: 'dishes#update', as: 'update_dish'
    delete '/dishes/:id', to: 'dishes#destroy', as: 'destroy_dish'
  end

  resources :restaurants do
    resources :items
  end
  
  resources :items
  root 'home#index'

  get '/categories', to: 'home#categories', as: 'categories'
  post '/restaurants/search', to: 'restaurants#search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  




end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :callories, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :dish
  belongs_to :restaurant
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id]) 
  end

  # GET /items/new
  def new
    @item = Item.new
    @dishes = Dish.all
    @restaurants = Restaurant.all
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {}).permit(:name, :callories,:price, :dish_id, :restaurant_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<h1>Items</h1>

<% @items.each do |item| %>
  <div>
    <h2>Name: <%= item.name %></h2>
    <p>
      <%= link_to 'Show', item_path(item), class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>

<%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %> 

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_with(model: @item, url: items_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :callories %>
    <%= form.text_field :callories %>
  </div>
  <div>
    <%= form.label :dish_id %>
    <%= form.collection_select :dish_id, @dishes, :id, :name %>
  </div>
  <div>
    <%= form.label :restaurant_id %>
    <%= form.collection_select :restaurant_id, @restaurants, :id, :name %>
  </div>
  <div>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back to Items', items_path, class: 'btn btn-primary' %>

app/views/items/show.html.erb
<h1>Item Details</h1>

<p style="color: green"><%= notice %></p>

<h2>Name: <%= @item.name %></h2>
<!-- Display other attributes of the item as needed -->

<%= link_to 'Edit Item', edit_item_path(@item), class: 'btn btn-primary' %>
<%= button_to 'Destroy Item', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to 'Back to Items', items_path, class: 'btn btn-primary' %>